"""ExperienceRetriever — fetch recent trade experiences for prompt injection.

V0.1 implementation: simple tag filter on (account_id, symbol, regime,
strategy_mode) with recency ordering. V0.2+ adds pgvector similarity search
once experience_summaries start being generated by the Attribution AI.

The retriever returns lightweight ExperienceSummary dataclasses rather than
SQLAlchemy rows so prompt composition doesn't have to know about ORM internals.
"""
from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from src.models.experience_v2 import ExperienceV2


@dataclass
class ExperienceSummary:
    """Plain data for prompt injection — no ORM dependency."""
    symbol: str
    regime_at_open: str | None
    strategy_mode: str | None
    pnl_pct: float | None
    hold_duration: int | None  # seconds
    exit_reason: str | None


class ExperienceRetriever:
    def __init__(self, session: Session):
        self._session = session

    def top_k(
        self,
        *,
        account_id: int,
        symbol: str,
        regime: str | None = None,
        strategy_mode: str | None = None,
        limit: int = 5,
    ) -> list[ExperienceSummary]:
        """Return up to `limit` most-recent experiences matching the filters.

        regime / strategy_mode are optional; when None the filter is skipped.
        Ordering: `created_at DESC` (most recent first).
        """
        stmt = select(ExperienceV2).where(
            ExperienceV2.account_id == account_id,
            ExperienceV2.symbol == symbol,
        )
        if regime is not None:
            stmt = stmt.where(ExperienceV2.regime_at_open == regime)
        if strategy_mode is not None:
            stmt = stmt.where(ExperienceV2.strategy_mode == strategy_mode)
        stmt = stmt.order_by(ExperienceV2.created_at.desc()).limit(limit)

        rows = self._session.execute(stmt).scalars().all()
        return [
            ExperienceSummary(
                symbol=r.symbol,
                regime_at_open=r.regime_at_open,
                strategy_mode=r.strategy_mode,
                pnl_pct=float(r.pnl_pct) if r.pnl_pct is not None else None,
                hold_duration=r.hold_duration,
                exit_reason=r.exit_reason,
            )
            for r in rows
        ]
