"""init_schema_after_v37_refactor

Revision ID: 602c525cfbcd
Revises: 
Create Date: 2026-05-01 11:27:27.323650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602c525cfbcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('available_balance_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_invocations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_invocations_occurred_at', 'agent_invocations', ['occurred_at'], unique=False)
    op.create_index('ix_agent_invocations_prompt_template_id', 'agent_invocations', ['prompt_template_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('entry_type', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_size_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('strategy_mode', sa.String(length=30), nullable=True),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('prompt_input', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('proposal_draft_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('factor_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles_symbol_timeframe_open_time', 'candles', ['symbol', 'timeframe', 'open_time'], unique=True)
    op.create_table('daily_reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('max_single_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('risk_events_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('adjustments_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_inbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('consumer_name', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_inbox_consumer_name_event_id', 'event_inbox', ['consumer_name', 'event_id'], unique=True)
    op.create_table('event_outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_outbox_event_id', 'event_outbox', ['event_id'], unique=False)
    op.create_table('experience_store',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('strategy_mode', sa.String(length=30), nullable=False),
    sa.Column('indicator_snapshot', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=False),
    sa.Column('holding_seconds', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_table('experience_summaries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('generated_by_agent', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_summaries_experience_id', 'experience_summaries', ['experience_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('regime_at_open', sa.String(length=20), nullable=True),
    sa.Column('strategy_mode', sa.String(length=30), nullable=True),
    sa.Column('factor_snapshot_at_open_id', sa.BigInteger(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('hold_duration', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiences_trade_id', 'experiences', ['trade_id'], unique=False)
    op.create_table('factor_candidates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('proposed_by_agent', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('formula_code_ref', sa.String(length=200), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_report_json', sa.JSON(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_definitions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula_code_ref', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_definitions_name_version', 'factor_definitions', ['name', 'version'], unique=True)
    op.create_table('factor_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('factor_def_versions_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_snapshots_unique', 'factor_snapshots', ['account_id', 'trading_mode', 'symbol', 'timeframe', 'open_time'], unique=True)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema20', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('atr', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_ma', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_diagnoses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('triggered_by_event_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('pattern_matched', sa.String(length=100), nullable=True),
    sa.Column('llm_narrative', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('binance_order_id', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_table('parameter_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposed_by_agent', sa.String(length=40), nullable=True),
    sa.Column('validated_by', sa.String(length=40), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_template', sa.Text(), nullable=False),
    sa.Column('user_template', sa.Text(), nullable=False),
    sa.Column('variables_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_templates_name_version', 'prompt_templates', ['name', 'version'], unique=True)
    op.create_table('proposal_drafts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('rendered_system', sa.Text(), nullable=False),
    sa.Column('rendered_user', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regime_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_position_size_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('max_single_risk_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('min_rr_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sl_atr_min_mult', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sl_atr_max_mult', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('regime_thresholds_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_decisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('shadow_run_id', sa.String(length=64), nullable=False),
    sa.Column('real_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('proposal_json', sa.JSON(), nullable=False),
    sa.Column('parameter_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shadow_decisions_shadow_run_id', 'shadow_decisions', ['shadow_run_id'], unique=False)
    op.create_table('shadow_evaluations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('shadow_decision_id', sa.Integer(), nullable=False),
    sa.Column('real_trade_id', sa.BigInteger(), nullable=True),
    sa.Column('shadow_pnl_sim', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('real_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('diff', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shadow_evaluations_shadow_decision_id', 'shadow_evaluations', ['shadow_decision_id'], unique=False)
    op.create_table('strategy_scores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_mode', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pnl_sum', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('false_breakout_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('regime_fit_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_scores_key', 'strategy_scores', ['account_id', 'strategy_mode', 'symbol', 'regime', 'window'], unique=True)
    op.create_table('symbol_configs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('max_position_size_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('trade_attributions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('by_symbol', sa.JSON(), nullable=True),
    sa.Column('by_time_bucket', sa.String(length=40), nullable=True),
    sa.Column('by_exit_reason', sa.String(length=30), nullable=True),
    sa.Column('by_factors_json', sa.JSON(), nullable=True),
    sa.Column('factor_contributions_json', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_attributions_trade_id', 'trade_attributions', ['trade_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=10), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=False),
    sa.Column('strategy_mode', sa.String(length=30), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('holding_seconds', sa.BigInteger(), nullable=True),
    sa.Column('ai_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('open_order_id', sa.BigInteger(), nullable=True),
    sa.Column('close_order_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（UTC）'),
    sa.Column('enable_flag', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='是否有效（False=禁用，业务过滤用）'),
    sa.Column('delete_flag', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='是否软删（True=已删除，物理保留）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###

    # ── Bootstrap 默认 account / risk_profile（id=1）────────────────────────────
    # 业务代码很多地方 default=1，依赖此行存在；
    # 历史上由旧 init_schema migration 引导，重建后保留同样的语义。
    op.execute(
        "INSERT INTO accounts (id, name, exchange, trading_mode, enabled) "
        "VALUES (1, 'default', 'binance', 'testnet', TRUE) "
        "ON CONFLICT (id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO risk_profiles ("
        "  id, account_id, name, active, version,"
        "  max_position_size_pct, max_daily_loss_pct, max_consecutive_losses, max_single_risk_pct,"
        "  min_rr_ratio, sl_atr_min_mult, sl_atr_max_mult"
        ") VALUES ("
        "  1, 1, 'default', TRUE, 1,"
        "  0.20, 0.03, 3, 0.01,"
        "  1.5, 0.5, 5.0"
        ") ON CONFLICT (id) DO NOTHING"
    )
    op.execute("UPDATE accounts SET risk_profile_id = 1 WHERE id = 1")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_index('ix_trade_attributions_trade_id', table_name='trade_attributions')
    op.drop_table('trade_attributions')
    op.drop_table('system_settings')
    op.drop_table('symbol_configs')
    op.drop_index('ix_strategy_scores_key', table_name='strategy_scores')
    op.drop_table('strategy_scores')
    op.drop_index('ix_shadow_evaluations_shadow_decision_id', table_name='shadow_evaluations')
    op.drop_table('shadow_evaluations')
    op.drop_index('ix_shadow_decisions_shadow_run_id', table_name='shadow_decisions')
    op.drop_table('shadow_decisions')
    op.drop_table('risk_profiles')
    op.drop_table('risk_events')
    op.drop_table('regime_snapshots')
    op.drop_table('proposal_drafts')
    op.drop_index('ix_prompt_templates_name_version', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_table('positions')
    op.drop_table('parameter_versions')
    op.drop_table('orders')
    op.drop_table('ops_diagnoses')
    op.drop_table('indicator_snapshots')
    op.drop_index('ix_factor_snapshots_unique', table_name='factor_snapshots')
    op.drop_table('factor_snapshots')
    op.drop_index('ix_factor_definitions_name_version', table_name='factor_definitions')
    op.drop_table('factor_definitions')
    op.drop_table('factor_candidates')
    op.drop_index('ix_experiences_trade_id', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index('ix_experience_summaries_experience_id', table_name='experience_summaries')
    op.drop_table('experience_summaries')
    op.drop_table('experience_store')
    op.drop_index('ix_event_outbox_event_id', table_name='event_outbox')
    op.drop_table('event_outbox')
    op.drop_index('ix_event_inbox_consumer_name_event_id', table_name='event_inbox')
    op.drop_table('event_inbox')
    op.drop_table('decision_reviews')
    op.drop_table('daily_reports')
    op.drop_index('ix_candles_symbol_timeframe_open_time', table_name='candles')
    op.drop_table('candles')
    op.drop_table('audit_logs')
    op.drop_table('ai_decisions')
    op.drop_index('ix_agent_invocations_prompt_template_id', table_name='agent_invocations')
    op.drop_index('ix_agent_invocations_occurred_at', table_name='agent_invocations')
    op.drop_table('agent_invocations')
    op.drop_table('accounts')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
